# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0015_auto_20170627_0549'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferece', models.PositiveSmallIntegerField(choices=[(1, 'System'), (2, 'User')], default=1)),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'articles'), (2, 'Tags')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
