# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_usertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'articles'), (2, 'Tags'), (3, 'Ratings')], default=2),
        ),
    ]
