# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170602_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=None, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
