# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170607_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
