# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='contentmeta',
            options={'ordering': ['id']},
        ),
    ]
