# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
