# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_tag_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
