# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_contentrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
