# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_articleview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleview',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.Author'),
        ),
    ]
