# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20170621_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleview',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleview',
            name='author',
        ),
        migrations.DeleteModel(
            name='ArticleView',
        ),
    ]
