# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20170627_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
