# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20170630_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article_tags', to='tags.Tag'),
        ),
    ]
