# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20170803_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='in_home',
            field=models.BooleanField(default=False),
        ),
    ]
