# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:09
from __future__ import unicode_literals

from django.db import migrations
# from articles.models.tag import Tag as OldTag
# from tags.models.tag import Tag

def move_tags(apps, schema_editor):
    OldTag = apps.get_model('articles', 'Tag')
    Tag = apps.get_model('tags', 'Tag')

    tags = OldTag.objects.all()
    for _tag in tags:
        new_tag = Tag.objects.get_or_create(name=_tag.name, slug=_tag.slug)

class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(move_tags),
    ]
